/*******************************************************************************
  WARNING: This file was generated by a tool and changes to this file
           will be lost when this file is regenerated.
********************************************************************************/

/*******************************************************************************
   Drop database if it exists
********************************************************************************/
IF EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE name = N'AureliaBooks')
BEGIN
	ALTER DATABASE [AureliaBooks] SET OFFLINE WITH ROLLBACK IMMEDIATE;
	ALTER DATABASE [AureliaBooks] SET ONLINE;
	DROP DATABASE [AureliaBooks];
END

GO

/*******************************************************************************
   Create database
********************************************************************************/
CREATE DATABASE [AureliaBooks];
GO

USE [AureliaBooks];
GO

/*******************************************************************************
   Create Tables
********************************************************************************/
